---
- name: destroy servers
  hosts: localhost
  gather_facts: False

  tasks:
    - name: Include cluster vars
      include_vars:
        file: cluster/config.yaml  
    - name: destroy master
      sl_vm:
        hostname: "{{ item }}"
        domain: example.com
        datacenter: "{{ sl_datacenter|default('dal09') }}"
        tags: "{{ item }},icp,master"
        state: absent
      with_items:
        - icp-master01

    - name: create workers
      sl_vm:
        hostname: "{{ item }}"
        domain: example.com
        datacenter: "{{ sl_datacenter|default('dal09') }}"
        tags: "{{ item }},icp,worker"
        state: absent
      with_items:
        - icp-worker01
        - icp-worker02
